apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  selector:
    app: vsftpd
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: ftps
      port: 21
      targetPort: 21
    - protocol: TCP
      name: port-passv
      port: 21100
      targetPort: 21100