apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: vsftpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vsftpd
  template:
    metadata:
      labels:
        app: vsftpd
    spec:
      containers:
        - name: ftps
          image: ftps_img
          imagePullPolicy: Never
          ports:
            - containerPort: 21
            - containerPort: 21100