apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
spec:
  type: ClusterIP
  selector:
    app: influxdb
  ports:
    - protocol: TCP     
      port: 8086
      targetPort: 8086
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influx-pvc
  labels:
    app: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi