apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  ports:
    - protocol: TCP     
      port: 5050
      targetPort: 5050